// Code generated by bundle. DO NOT EDIT.

package resources

import (
	"github.com/golangee/bundle"
	"time"
)

// BundleVersion contains the hash of all embedded files and their bundle options.
const BundleVersion = "84e96b115081af6c8081210f9ebd864814c913b9476dc318ac10c6241a48e3ba"

const (
	DocOpenapiApidocJson = "/doc/openapi/apidoc.json"
)

// Bundle contains all embedded named resources.
var Bundle = bundle.Make(

	bundle.NewResource("/doc/openapi/apidoc.json", 2897, 493, time.Unix(1594714913, 68159230), "33e4a1db8c9df4dd89f8bf1fb30136ae4229526de81e48fbf5bc78bbbe12a0f9", true, true, true, blob_33e4a1db8c9df4dd89f8bf1fb30136ae4229526de81e48fbf5bc78bbbe12a0f9),
)

const blob_33e4a1db8c9df4dd89f8bf1fb30136ae4229526de81e48fbf5bc78bbbe12a0f9 = ")c-nb*!^Xk:1H!sR,1a3V&%bEg:F<Loa5fee9&_n]/.apl_7$UTr0$\\a_hlbY.jV:p?RD(M53b?2*tg8c$hD\"6VJ+aG7QEF7C3gs9@tCg]D)>_#brdGI(o+S\"bg4C7=G9A2Ze]SDid`RrtolP!:a,5<\\g0NpDUDtZ%_ssEWJ0^+7G,WC&!d`OGGPU$B\"-W1sQ`>JfjZ1Z\"\\RU1lHf-%t?)qHQcr.WYCcs\"M1=O&fkf5T=S>GfIX7i>I4M#UU\\*.<q`\"r,YD!^=VMfa7)lIIH]V2Oi?i;&p]>it\\gpdHf``f[h&a@`n>!S$.+O._Xe^W\"fU@m@%tD3XCPM_XLh@oc8oZ)+'<U%9_NH$g1.4rV2Yk4Ch2%INPAB4Vo?^Oj9nPBB`gdd_n8C337lDX0\\OqP)!X5?Mp#u9eKuShIK67bOBqbsX,?2.Q'l>S/_0N9tT)UCA?^X5S.D]p+AG?mh2maHD<)(tqn%^U'Ma*f*G*>\\iCuo:2:q3Ro*p@:(*Q]lg8VqsJb-ZE6UDQIm3KbAmW\\M,AB0i3a>A97nQ]a,YR`dE54CPg5dUcA!e@J^J8(ek^Pk@.2;;C$^<%'c'&D2E3do3$>r!k>$^b/l,'36%[/;U,bBoa'R8t>t$4K0m*`PVKMP_BdCe^-:Y=?KiTl#6pF;d<[q.*j5=St1?(G/Zd2)qsi%3&.:WiFonr:A7ri;0n/!,AMXC2<(D'o+<jXeNq?/n83*][^=')+j/Mk@X=LGE0>OZ@gf,4%od\"p!+e<V:.-HIs-&mGQXWl`k23eEjK`Ga&tbSK2?G?9Hdt0/8SU/mTbFG?D4C(r:\\+NfgP%^SSh7M-V,q(n4G3M.6lRV%VphPXIQ\\a0[u+EDab8J.\"]Q]77W-kiQT6ZcQCfSGhRW$a81ni;'1g+Uiar&7^>_S#AJQuk]OcYBPHORUe!E_23kS]m?`9Qd1.?%hBIb.>^3fS(AKtkH_m&]5:M4ISeK9l/g\"K!!><g>,C.gphTRTZ@DD(]jb=&07.^h_\"=[A-T7_icSZ'&N4O5;dRKOXa%75hI,RD93&*hd4G[ZJ`P\"Fe%GZ,%gs"
