// Code generated by bundle. DO NOT EDIT.

package resources

import (
	"github.com/golangee/bundle"
	"time"
)

// BundleVersion contains the hash of all embedded files and their bundle options.
const BundleVersion = "b8bdce5e41fbb927fc12452016852a4056f9dc9d995599aa41cd81e043fca294"

const (
	DocOpenapiApidocJson = "/doc/openapi/apidoc.json"
)

// Bundle contains all embedded named resources.
var Bundle = bundle.Make(

	bundle.NewResource("/doc/openapi/apidoc.json", 3973, 493, time.Unix(1594724296, 821791531), "a09755a5b7e699a2ce183f11e00ab3b3eab4a5155155547d35038c767e2ece64", true, true, true, blob_a09755a5b7e699a2ce183f11e00ab3b3eab4a5155155547d35038c767e2ece64),
)

const blob_a09755a5b7e699a2ce183f11e00ab3b3eab4a5155155547d35038c767e2ece64 = ")h\\_e*!^Y^cUH2!%;`B6TsQDWQaV%[WRL\\k1(luI*Re<6GY8^4G`1_!Ipr(`dHTr^8,K\\lmin`/BoUL=be-+/>spR7mX@Gi>7mukhC5\"S/TIG>C_;9kiCGO.KT+4F+&GeT<DaMJ5jnoNeF=QTQhWd7*>;9D1D$T(c3!DoBGk:b1%3m(,.$\\,^:]qc%heH4mM/8YEIEDD=i?oY^N=e,VD\\0!$iWL'<m]M'a]^s(0Z[msMs?<X\"Ncm-8na&45p`pN#C:J-$bXL%*m!l-M+M'?AYac?(*Yq?NSkE)3Qr^H5^sMcjUk/QJeUan-Qk\\H06Lo)l6@/R8J0-'-1$SFJ)&1hJ%M>/@n?<\\W!U7/CMQL>M1D.\"78,<Xq8@sBKUKd\"MV`bFZP@N4i/NW;8PT[1M*sf;&<gr7\"lB.[WId%'Y9u1E#HY?l7:9\"W'&lA'D&:s[>\\5ML`?oj/Z(uh_j2$f8lLg4Q`6K_VK.na<6e3nuPjOcfClH,E4cm\"%#$S5V0spn;`T3kQVTRX4?F5Aj-<^\"[OBIQnoq/<hp_Wq5p0pLq9u)?\"o^<4dma\"\\@QMmg^H7i!:5tqXLm:dA5!KuHPL?%StAg\\O254N=qZNcU<QY7l1h5DVo(I;R8hAYB5Z3.&CDur/t#KBOXZ7J@]&5^XH[AXqG6PRK[i),p%=\\Jo<n_*Gh<JQYITg\\GTm1m=^QDVcPU_Uf++??l&C(XBi<1-\"&ch6T1dtVa@!cQTd&ps5j\"!Iq/(f#r%Rc?SGG/LYmb:i5;d&q-m/VeI%%.IbMFJjC%011sF@M=d7[a2or4#NoBKa=0p?a[\"Z^Xl1.6_MboIj77sUGRcI1WYc!</t*M9^73$'IpsZq'$J\\E@%0-Kq0/Ta%b`5D4-q4U^`!SH@e0HXM?^$D^7l+Dk?HgE:3^RD&48791n8RX55fYq?.^')VDOP)r^E9\"U_iIGLqrr,ag@7A,6c6;j4n*F6u)T$\\E;]iVN3?>biK$kC59g?=D![\\nAY]0$OH0L:7:<`O)]W0R:3^'A&VM/>A:.0`^dbPHQTaJB6f%o%-]410X>Qj@m!?;Wfqe[?XiC%P1V08`pVTnS8tPG%>5cCko0.)?'+=qR?T^bF.*p(q-BgP=rVGNfC,`-Lgr260K;R\"XL65d/P_/]q>N_"
