// Code generated by bundle. DO NOT EDIT.

package resources

import (
	"github.com/golangee/bundle"
	"time"
)

// BundleVersion contains the hash of all embedded files and their bundle options.
const BundleVersion = "1111fe20e95516072c00d103253cf3ba8c70c3d7b173a74fcc351da9792073b4"

const (
	DocOpenapiApidocJson = "/doc/openapi/apidoc.json"
)

// Bundle contains all embedded named resources.
var Bundle = bundle.Make(

	bundle.NewResource("/doc/openapi/apidoc.json", 890, 493, time.Unix(1590658037, 106132765), "def2e0876b958c86ee37d0d3b206061a5baeff7fa16ce6105065df233d02f7f4", true, true, true, blob_def2e0876b958c86ee37d0d3b206061a5baeff7fa16ce6105065df233d02f7f4),
)

const blob_def2e0876b958c86ee37d0d3b206061a5baeff7fa16ce6105065df233d02f7f4 = ")gMN.*!^Y^cV5AgCpTFTWC?Nj[_b8:[T&Z=7+f81L.:BQ,1\\e+?%)bP=s+3Y\\3Th(qmn?tA>AY?!?Ps/l/diAD\\'3TH8UW\"6TkSpga7`=Z0\"=$>9H935oFkFfVN(RK\\q<r$[>jggLD,5!p4^T!rLZ!hJHNgV%;1)6uJ3'3XD7i<5GS#*\"Hi;h,pP0_LYcL3eZB+fUTcP>C+bT4>gW1%BJ`I!R0P,aZS8X;[=1]@m+<`7\\\\c'7r&be,%*s/:o\"p7A&rsU(LSu0.qT@+\"+]fi+:,$,D&5[!,F%t4D\"c;Sbo\\6RJHdOCeA8R1i\",sW6NZoqONG'>!eZ\\0c_$6;dJA,,]IQO0gBNA:mmaXpmWR08d4I83g/m'*%!EeY%j<$Qgj)>SI2EmA:?$@d7dh+PG%iq;EgF\"CL6B3.d9^o!*W"
