// Code generated by sqlm. DO NOT EDIT.

package mysql

type Migration = struct {
	Group      string
	Version    int64
	Statements []string
	ScriptName string
}

var Migrations = []Migration{
	{
		Group:   "users",
		Version: 1,
		Statements: []string{
			"CREATE TABLE `user` ( id binary(16) PRIMARY KEY, firstname varchar(255) NOT NULL, lastname varchar(255), login varchar(255) NOT NULL )",
		},
		ScriptName: "0001_user.sql",
	},
	{
		Group:   "users",
		Version: 2,
		Statements: []string{
			"ALTER TABLE user DROP COLUMN lastname",
			"ALTER TABLE user ADD COLUMN blub",
			"ALTER TABLE venue ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW()",
		},
		ScriptName: "0002_alteruser.sql",
	},
}
