// Code generated by sqlc. DO NOT EDIT.

package mysql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	ListUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
